import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { poppins } from "@/app/ui/fonts";
import "./globals.css";
import SideNav from "@/app/ui/sidenav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`} 
      >
        <div className="flex py-10 px-50 h-screen flex-col bg-[#121212] md:flex-row md:overflow-hidden ">
          <div className="w-full flex-none rounded-xl bg-[#1E1E1F] md:w-64">
            <SideNav />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}      
          </div>
        </div>

      </body>
    </html>
  );
}
