import type { Metadata } from "next";
import { poppins } from "@/app/ui/fonts";
import "./globals.css";
import SideNav from "@/app/ui/sidenav/sidenav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`} 
      >
        <div className="flex px-4 py-2 gap-4 h-screen bg-[#121212] md:flex-row md:overflow-hidden">
          <div className="p-6 w-full flex-none rounded-xl bg-[#1E1E1F] md:w-64">
            <SideNav />
          </div>
          <div className="flex rounded-xl bg-[#1E1E1F] p-6 md:overflow-y-auto md:p-1 flex-1">
            {children}      
          </div>
        </div>
      </body>
    </html>
  );
}
